import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import { Header } from '@/ui/components/header';

import './globals.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} mb-8 mx-3 md:mx-8 lg:mx-12 xl:mx-32`}>
        <Header />
        {children}
      </body>
    </html>
  );
}
